/*
 * Google OAuth2 API
 * Obtains end-user authorization grants for use with other Google APIs.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Tokeninfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T15:30:00.427259+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class Tokeninfo {
  public static final String SERIALIZED_NAME_AUDIENCE = "audience";
  @SerializedName(SERIALIZED_NAME_AUDIENCE)
  @javax.annotation.Nullable
  private String audience;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  @javax.annotation.Nullable
  private String email;

  public static final String SERIALIZED_NAME_EXPIRES_IN = "expires_in";
  @SerializedName(SERIALIZED_NAME_EXPIRES_IN)
  @javax.annotation.Nullable
  private Integer expiresIn;

  public static final String SERIALIZED_NAME_ISSUED_TO = "issued_to";
  @SerializedName(SERIALIZED_NAME_ISSUED_TO)
  @javax.annotation.Nullable
  private String issuedTo;

  public static final String SERIALIZED_NAME_SCOPE = "scope";
  @SerializedName(SERIALIZED_NAME_SCOPE)
  @javax.annotation.Nullable
  private String scope;

  public static final String SERIALIZED_NAME_USER_ID = "user_id";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  @javax.annotation.Nullable
  private String userId;

  public static final String SERIALIZED_NAME_VERIFIED_EMAIL = "verified_email";
  @SerializedName(SERIALIZED_NAME_VERIFIED_EMAIL)
  @javax.annotation.Nullable
  private Boolean verifiedEmail;

  public Tokeninfo() {
  }

  public Tokeninfo audience(@javax.annotation.Nullable String audience) {
    this.audience = audience;
    return this;
  }

  /**
   * Who is the intended audience for this token. In general the same as issued_to.
   * @return audience
   */
  @javax.annotation.Nullable
  public String getAudience() {
    return audience;
  }

  public void setAudience(@javax.annotation.Nullable String audience) {
    this.audience = audience;
  }


  public Tokeninfo email(@javax.annotation.Nullable String email) {
    this.email = email;
    return this;
  }

  /**
   * The email address of the user. Present only if the email scope is present in the request.
   * @return email
   */
  @javax.annotation.Nullable
  public String getEmail() {
    return email;
  }

  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }


  public Tokeninfo expiresIn(@javax.annotation.Nullable Integer expiresIn) {
    this.expiresIn = expiresIn;
    return this;
  }

  /**
   * The expiry time of the token, as number of seconds left until expiry.
   * @return expiresIn
   */
  @javax.annotation.Nullable
  public Integer getExpiresIn() {
    return expiresIn;
  }

  public void setExpiresIn(@javax.annotation.Nullable Integer expiresIn) {
    this.expiresIn = expiresIn;
  }


  public Tokeninfo issuedTo(@javax.annotation.Nullable String issuedTo) {
    this.issuedTo = issuedTo;
    return this;
  }

  /**
   * To whom was the token issued to. In general the same as audience.
   * @return issuedTo
   */
  @javax.annotation.Nullable
  public String getIssuedTo() {
    return issuedTo;
  }

  public void setIssuedTo(@javax.annotation.Nullable String issuedTo) {
    this.issuedTo = issuedTo;
  }


  public Tokeninfo scope(@javax.annotation.Nullable String scope) {
    this.scope = scope;
    return this;
  }

  /**
   * The space separated list of scopes granted to this token.
   * @return scope
   */
  @javax.annotation.Nullable
  public String getScope() {
    return scope;
  }

  public void setScope(@javax.annotation.Nullable String scope) {
    this.scope = scope;
  }


  public Tokeninfo userId(@javax.annotation.Nullable String userId) {
    this.userId = userId;
    return this;
  }

  /**
   * The obfuscated user id.
   * @return userId
   */
  @javax.annotation.Nullable
  public String getUserId() {
    return userId;
  }

  public void setUserId(@javax.annotation.Nullable String userId) {
    this.userId = userId;
  }


  public Tokeninfo verifiedEmail(@javax.annotation.Nullable Boolean verifiedEmail) {
    this.verifiedEmail = verifiedEmail;
    return this;
  }

  /**
   * Boolean flag which is true if the email address is verified. Present only if the email scope is present in the request.
   * @return verifiedEmail
   */
  @javax.annotation.Nullable
  public Boolean getVerifiedEmail() {
    return verifiedEmail;
  }

  public void setVerifiedEmail(@javax.annotation.Nullable Boolean verifiedEmail) {
    this.verifiedEmail = verifiedEmail;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tokeninfo tokeninfo = (Tokeninfo) o;
    return Objects.equals(this.audience, tokeninfo.audience) &&
        Objects.equals(this.email, tokeninfo.email) &&
        Objects.equals(this.expiresIn, tokeninfo.expiresIn) &&
        Objects.equals(this.issuedTo, tokeninfo.issuedTo) &&
        Objects.equals(this.scope, tokeninfo.scope) &&
        Objects.equals(this.userId, tokeninfo.userId) &&
        Objects.equals(this.verifiedEmail, tokeninfo.verifiedEmail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(audience, email, expiresIn, issuedTo, scope, userId, verifiedEmail);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tokeninfo {\n");
    sb.append("    audience: ").append(toIndentedString(audience)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    expiresIn: ").append(toIndentedString(expiresIn)).append("\n");
    sb.append("    issuedTo: ").append(toIndentedString(issuedTo)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    verifiedEmail: ").append(toIndentedString(verifiedEmail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("audience", "email", "expires_in", "issued_to", "scope", "user_id", "verified_email"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Tokeninfo
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Tokeninfo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Tokeninfo is not found in the empty JSON string", Tokeninfo.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Tokeninfo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Tokeninfo` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("audience") != null && !jsonObj.get("audience").isJsonNull()) && !jsonObj.get("audience").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `audience` to be a primitive type in the JSON string but got `%s`", jsonObj.get("audience").toString()));
      }
      if ((jsonObj.get("email") != null && !jsonObj.get("email").isJsonNull()) && !jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
      if ((jsonObj.get("issued_to") != null && !jsonObj.get("issued_to").isJsonNull()) && !jsonObj.get("issued_to").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `issued_to` to be a primitive type in the JSON string but got `%s`", jsonObj.get("issued_to").toString()));
      }
      if ((jsonObj.get("scope") != null && !jsonObj.get("scope").isJsonNull()) && !jsonObj.get("scope").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `scope` to be a primitive type in the JSON string but got `%s`", jsonObj.get("scope").toString()));
      }
      if ((jsonObj.get("user_id") != null && !jsonObj.get("user_id").isJsonNull()) && !jsonObj.get("user_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `user_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("user_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Tokeninfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Tokeninfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Tokeninfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Tokeninfo.class));

       return (TypeAdapter<T>) new TypeAdapter<Tokeninfo>() {
           @Override
           public void write(JsonWriter out, Tokeninfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Tokeninfo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Tokeninfo given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Tokeninfo
   * @throws IOException if the JSON string is invalid with respect to Tokeninfo
   */
  public static Tokeninfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Tokeninfo.class);
  }

  /**
   * Convert an instance of Tokeninfo to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

